"""Apollo client constants."""

DEFAULT_CLUSTER = "default"
DEFAULT_ENV = "DEV"
DEFAULT_NAMESPACE = "application"
DEFAULT_TIMEOUT = 10
DEFAULT_CYCLE_TIME = 30
DEFAULT_CONFIG_SERVER_PORT = 8080
DEFAULT_FALLBACK_PORT = 8090
DEFAULT_NOTIFICATION_ID = -1
LONG_POLL_READ_TIMEOUT = 90

META_SERVICES_CONFIG_PATH = "services/config"

HTTP_HEADER_AUTHORIZATION = "Authorization"
HTTP_HEADER_TIMESTAMP = "Timestamp"
AUTHORIZATION_FORMAT = "Apollo {}:{}"

CONFIGS_PATH_TEMPLATE = "configs/{app_id}/{cluster}/{namespace}"
NOTIFICATIONS_PATH = "notifications/v2"

ENV_CACHE_DIR = "APOLLO_CACHE_DIR"
